  
pipeline {
   agent any

   stages {
      stage('Check Versions') {
         steps {
            sh 'gcloud --version'
            sh 'docker --version'
            sh 'nodejs --version'
            sh 'terraform --version'
         }
      }
      stage('Pull Repo') {
           steps {
              dir('./devops-certification/frontend') {
                  sh 'git pull'
              }
          }
      }
      stage('SonarCube Test') {
          steps {
              dir('./devops-certification/frontend') {
                  sh '/home/robmschn/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=deploy-frontend -Dsonar.sources=. -Dsonar.host.url=http://34.73.170.34:9000 -Dsonar.login=90eef76f2043830e1c82cad5426ad270bc94fd8c'
              }
          }
      }
      stage('NPM Test') {
          steps {
            dir('./devops-certification/frontend') {
                sh 'npm install'
                sh 'npm test'
            }
          }
    }
      stage('Build and Submit') {
        steps {
            dir('./devops-certification/frontend') {
                sh 'gcloud builds submit -t gcr.io/devops-certification-279819/frontend:v1.${BUILD_NUMBER} .'
            }
        }
    }
      stage('Deploy to Kubernetes') {
        steps {
            dir('./devops-certification/frontend') {
                sh 'terraform init'
                sh 'gcloud container clusters get-credentials cluster1 --zone us-east1-c'
                sh 'TF_VAR_BUILD=${BUILD_NUMBER} terraform apply -auto-approve'
            }
        }
    }
   }
}
