pipeline {
   agent any

   stages {
      stage('Check Versions') {
         steps {
            sh 'gcloud --version'
            sh 'docker --version'
            sh 'nodejs --version'
         }
      }
   }
}
