pipeline {
   agent any

   stages {
      stage('Remove Old Build') {
          steps {
              sh 'rm -rf *'
          }
      }
      stage('Check Versions') {
         steps {
            sh 'gcloud --version'
            sh 'docker --version'
            sh 'nodejs --version'
         }
      }
      stage('Clone Repo') {
          steps {
              sh 'git clone https://github.com/robschn/devops-certification.git'
              sh 'ls'
          }
      }
    stage('Install dependencies') {
        dir('./devops-certification/backend')
          steps {
            sh 'pwd'
            sh 'npm install'
            sh 'npm test'
          }
    }
    stage('Test') {
      steps {
         sh 'npm test'
      }
    }
   }
}
